### ISSUE TITLE
Ask to switch git branch first

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#100]
I keep forgetting to press 'Y'.

Let's ask everything at the beginning.

**Comment by everestmz** [comment]
Not feasible right now - would require refactoring of `binary_providers.py`

**Comment by tanin47** [comment]
Asking everything upfront requires a different paradigm of structure.

This is because we need a way to figuring out all the questions. Ask all of them before executing any code. ... so, not at this time.
