### ISSUE TITLE
Log the whole stacktrace to logging pipeline

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#122]
I've just seen one user running unsuccessfully with `SystemExit` with no other info.

It'd be great to see the whole stacktrace.

**Comment by everestmz** [comment]
Do we want to just log the final trace, or all of them?

**Comment by tanin47** [comment]
Let's go with the whole thing. You can use `traceback.format_exception()` https://chrome-internal-review.googlesource.com/c/340649/3/src/common/logs.py#125

Append the formatted exception to the message field. It'll detect automatically by gcloud.
