### ISSUE TITLE
CFI chrome takes a long time because args.gn doesn't enable goma

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#134]
Let's force enabling goma for all cases.

**Comment by inferno-chromium** [comment]
enable goma should be default, you can add an optional flag to disable goma in case dev finds goma not being able to build.

**Comment by tanin47** [comment]
> enable goma should be default, you can add an optional flag to disable goma in case dev finds goma not being able to build.

Yes, I agree. I just edited the description to force enabling goma on all cases.

We already have the `--disable-goma` flag. So, we should be good for the disabling case.
