### ISSUE TITLE
Allow user to run testcase against an arbitrary job type

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#218]
There are two issues:
* Gestures on windows and on linux are in different formats.
* On windows, we can't parse `ASAN_OPTIONS` by splitting with `:` because some value contains `c:\`.

**Comment by tanin47** [comment]
This is tricky to implement. A workaround is to ask user to upload the testcase with a corresponding linux job type. (We have added this in the error message).

**Comment by inferno-chromium** [comment]
I think that is sufficient, closing.
