### ISSUE TITLE
No gclient sync when current flag is on

### ISSUE THREAD

**Issue by npm1** [google/clusterfuzz-tools#223]
Some clusterfuzz issues are related to third_party repositories, so gclient sync can't be called to verify a fix. Also "current" should really just mean the current state of the repo, third_parties included.

**Comment by tanin47** [comment]
That's a good point! Thank you for the suggestion.

**Comment by tanin47** [comment]
We remove `--disable-gclient` completely. It seems we can just use `--current` if `--current` doesn't run `gclient` (#224). Thanks again for the suggestion.

**Comment by tanin47** [comment]
Hmmm... we got another case where user would like to do `--current` with `gclient sync`. Because user do `git pull`.

These two things seems unnecessarily tangled.

We'll bring back `--disable-gclient`.

**Comment by tanin47** [comment]
We are bringing the `--disable-gclient` back on the version `1.2.0` (#280).
