### ISSUE TITLE
Add support for debugging symbols

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz-tools#238]
https://bugs.chromium.org/p/chromium/issues/detail?id=692620

Need to be careful about old builds. When we add a non-existent flag to older build, gn gen will fail.

**Comment by tanin47** [comment]
For this mode, we'll inject `sanitizer_keep_symbols = true` and `is_debug = true`. Then, we will print the chrome (prefixed by gdb) command and ask user to run it manually.

**Comment by tanin47** [comment]
It seems there are multiple ways of debugging Chromium (https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_debugging.md). It might not be worth automating all of them. 

We'll support only the most popular one. For other cases of debugging, the user can mix and match the command to achieve what the user wants.

Using ASAN with gdb (https://xstack.exascale-tech.com/wiki/index.php/Debugging_with_AddressSanitizer)

**Comment by tanin47** [comment]
We'll break before and after ASAN reporting an error with `gdb -ex 'b __asan::ReportGenericError' -ex 'b __sanitizer::Die' -ex run --args` (Ref: https://github.com/google/sanitizers/wiki/AddressSanitizerAndDebugger)

**Comment by tanin47** [comment]
Supported in #328
