### ISSUE TITLE
Show printf outputs when reproducing

### ISSUE THREAD

**Issue by npm1** [google/clusterfuzz-tools#247]
The tool is currently fine to verify that a testcase can be reproduced / has been fixed, but is not very good for debugging, so this will force the user to do the setup work for some harder testcases. Allowing printfs to show up would be a good way to help the user debug.

**Comment by tanin47** [comment]
Good point. In the meantime, could you `tail -f ~/.clusterfuzz/logs/output.log`? Thank you.

**Comment by tanin47** [comment]
I think we can simply print all stderr.

**Comment by npm1** [comment]
fprintf works, great! Could we have a blank line between the line starting with "Running: " and the stack trace? That is where the fprintfs will generally show up, and they are hard to find due to no blank lines.

**Comment by tanin47** [comment]
It's great that you can find a way to make it work!

Yes, a blank line would be nicer. I'll take a chance to reformat the output as well. Thank you for suggestion.

**Comment by npm1** [comment]
Printing all stderr could be useful. For instance when compiling fails, I have to go to the logs to figure out what happened, it would be better to just print out the compile errors on console.

**Comment by tanin47** [comment]
The below will be launched in the version 1.2.0.

* All stderr will be printed on screen. 
* Instead of a blank line, we colorise the 'Running:' instead. I hope this is good enough.
