### ISSUE TITLE
OAuth flow doesn't work when SSHing.

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz-tools#263]
It seems that webbrowser.open() can hang when it fails to open a browser (e.g. when SSHed), giving the user no way to manually open the link and enter the verification code.

Maybe we can add a flag here to not launch the browser?

**Comment by tanin47** [comment]
Good catch. We can catch the exception and say that we cannot open a browser and you have to go to the URL manually.

One question: if it cannot open a browser, can the machine launch Chrome?

**Comment by oliverchang** [comment]
The machine can launch Chrome, and in a SSH session not be able to because there's no DISPLAY set.

**Comment by tanin47** [comment]
Thanks for the explanation!

Fixed with #265. We simply ignore the exception.
