### ISSUE TITLE
Show errors in the CI logs

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#277]
Where there's an error, we should show it in the CI logs. It'll be more convenient for debugging.

**Comment by inferno-chromium** [comment]
probably also need first console output of testcase run as stacktrace

**Comment by tanin47** [comment]
There are 2 things:
* We can get the last 100 lines of `stderr` and `stdout`.
* We can define an exit code for each type of expected exception.

**Comment by tanin47** [comment]
This solves the error message problem #350 and #351.
