### ISSUE TITLE
Can't run 'reproduce' without Goma installed.

### ISSUE THREAD

**Issue by mwenge** [google/clusterfuzz-tools#288]
I'm not a Googler but I should still be able to run this right?

[robert@mwenge-desktop WebKit (726583-2)]$ ~/Downloads/clusterfuzz-1.2.0rc1.pex reproduce 6362170727333888 --current
Version: 1.2.0rc1
Path: /home/robert/.pex/code/f4adc88875316980e2d6254683e8b70472edf685/clusterfuzz/main.pyc
----- START -----
Reproducing testcase 6362170727333888
Downloading testcase information...

GomaNotInstalledError: Either goma is not installed, or $GOMA_DIR is not set. Please set up goma before continuing.
See go/ma to learn more.

Detailed log of this run can be found in: /home/robert/.clusterfuzz/logs/output.log

**Comment by inferno-chromium** [comment]
Please use --disable-goma flag. Let us know if you have any issues.
