### ISSUE TITLE
Fix long names

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz-tools#289]
Trying to shorten...
New name is: `testcase-5779892666105856-68c0d461ef4b10acbb0d47e8[redacted]3eb411ccc5e3523496245f5e678942cc52ab0058fb316b87ec0aba32f9f15618487f703f00631248e984b94be3f312216dbf1a1df3bc564c18838792deff9b8f7ea12f87db`.

`2017-05-30 08:10:45 URL:https://clusterfuzz.com/v2/testcase-detail/download-testcase?id=5779892666105856 [176] -> "testcase-5779892666105856-68c0d461ef4b10acbb0d47e8f[redacted]a1fbc5b680651b3eb411ccc5e3523496245f5e678942cc52ab0058fb316b87ec0aba32f9f15618487f703f00631248e984b94be3f312216dbf1a1df3bc564c18838792deff9b8f7ea12f87db" [1]`

Why do we use such long names for hashes. Also confusing message for user.

**Comment by tanin47** [comment]
This name is generated by the website. I guess it's the blobstore filename or something.

This is printed because it's a warning from wget saying the filename is too long. I'll find a way to hide the warning but not the error (if there's one).

**Comment by tanin47** [comment]
This is fixed in #297.

We also modified clusterfuzz not to generate a too-long filename.
