### ISSUE TITLE
There seems to be a stale `clusterfuzz` process on CI

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#299]
This can come from the fact that we redeploy the CI; the daemon is killed... but the chrome process is not killed.

**Comment by inferno-chromium** [comment]
i think we should do binary process cleanup after running every testcase (just like CF does, but maybe lighter version of that). that way, we dont leak bad state from one testcase into another (from stuck stale process).

**Comment by tanin47** [comment]
We are using process group and kill every process in the group. We'll see if the problem with the child process occurs. If it occurs, we'll implement the cleanup.

**Comment by tanin47** [comment]
Ok, this is because, when we kill python-daemon with `sv stop python-daemon`, which sends `SIGTERM` to python-daemon, its children are not killed. Therefore, we'll see `python2.7 /python-daemon/clusterfuzz reproduce 4782259122208768` being alive. And, somehow, `atexit.register` doesn't work.

This might cause a problem because 2 of `clusterfuzz` processes might be running, and it might try to checkout or run `gclient sync` at the same time.

Chrome or content_shell processes don't have any issue.

**Comment by tanin47** [comment]
The problem should go away with #317.
