### ISSUE TITLE
Include user's email in the logs.

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#305]
We authenticate them against clusterfuzz anyway, so we have their emails.

And using `$USER` is less robust.

**Comment by tanin47** [comment]
This seems to break our architecture. We don't  know the user's email when starting the reproduce tool. We only know about it later in time.

**Comment by inferno-chromium** [comment]
Is this really needed, if not, lets wontfix.

**Comment by tanin47** [comment]
It might not be worth doing it. Wontfix.
