### ISSUE TITLE
Add "-l" support to specify "-l" parameter of ninja

### ISSUE THREAD

**Issue by wangxianzhu** [google/clusterfuzz-tools#348]
The current default -l 15 parameter to ninja may be too low for high-end machines, especially when some GOMA configurations are used to utilize more local CPU resources. The build is slow and happens in batches: 1600 jobs are scheduled and build is super fast at first, then ninja waits for all of the 1600 jobs to finish and then runs only 1 job at a time for several minutes before scheduling new jobs when the load average drops below 15.

Need a way to specify higher -l parameter. The default -l parameter can also be based on number of CPU cores.

Proposed patch is attached.

[patch.txt](https://github.com/google/clusterfuzz-tools/files/1072866/patch.txt)

**Comment by tanin47** [comment]
Thank you for the patch. I'll put the patch in our 1.5.0 milestone, which will be launched next week.

**Comment by tanin47** [comment]
Done in #349
