### ISSUE TITLE
Use the layout tests that ClusterFuzz uses.

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#366]
We've found one case where using the layout tests within chromium source doesn't reproduce.

There are a few options:

1. Let's archive the layout tests whenever the layout tests is used. We don't need to rely on log-net-log mechanism.
2. Download the ClusterFuzz's layout tests. (This sounds like it'll break when we change the layout tests).

**Comment by tanin47** [comment]
We probably need to download the ClusterFuzz layout tests because each test folder in LayoutTests is not guaranteed to be self-contained (e.g. it might depends on a random file outside the folder).

**Comment by tanin47** [comment]
I think we'll need to add versioning to Clusterfuzz's layout tests. Otherwise, when we update the layout tests, there'll be no way to figure out if the change in the layout tests is the root cause.

**Comment by inferno-chromium** [comment]
There would be too many layouttests that we would need to archive then :( but yes lets brainstorm more on this.

**Comment by tanin47** [comment]
Yes, that looks like a problem since the LayoutTests.zip is 1.5GB.

**Comment by tanin47** [comment]
Since the layout tests can change over time, the best way is to fix log-net-log (or make a new flag that works like a dumb version of log-net-log).

**Comment by tanin47** [comment]
We are solving this with: https://bugs.chromium.org/p/chromium/issues/detail?id=715656

There's no change needed on the reproduce. But we might want to remove the layout-test hack.
