### ISSUE TITLE
We ask for CHROMIUM_SRC, but we actually use CHROME_SRC

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#38]
```
This is a chromium testcase, please define $CHROMIUM_SRC or enter your chromium
source location here:
```

The input here doesn't work with autocomplete as well.

It might be easier to raise an exception on this and ask user to set it.

**Comment by everestmz** [comment]
Would it make more sense to ave CHROMIUM_SRC anyways? Then it's just a matter of changing the BinaryDefinitions

**Comment by tanin47** [comment]
Yes, the name CHROMIUM_SRC makes more sense since the repo is chromium (as opposed to chrome).

**Comment by everestmz** [comment]
Ok, I'll just change the BinaryDefinitions in the supported jobs then.
