### ISSUE TITLE
Setting ASAN_OPTIONS while building with ninja might cause a crash

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#433]
We have found one case where the user sets `ASAN_OPTIONS="symbolize=1 detect_leaks=1"` and runs the reproduce tool. The reproduce tool fails on `ninja` with an ASAN stacktrace.

This is because, when `is_asan = true`, everything is built with ASAN including `genperf`, and `genperf` seems to be have an ASAN bug (https://bugs.chromium.org/p/chromium/issues/detail?id=382380).

@Dor1s suggests that we simply remove `ASAN_OPTIONS` and every other sanitizers' envs when running `ninja`.

**Comment by tanin47** [comment]
I can reproduce this on my machine as well.

**Comment by inferno-chromium** [comment]
Yes correct, just unset *SAN_OPTIONS, others like MSAN_OPTIONS etc can have same consequences.

**Comment by tanin47** [comment]
Special thanks to @Dor1s for helping. I'll turn off every `*SAN_OPTIONS`.

**Comment by Dor1s** [comment]
Found this list on CF side, let's check all of those + probably LSAN:

```python
SUPPORTED_MEMORY_TOOLS_FOR_OPTIONS = ['ASAN', 'CFI', 'MSAN', 'TSAN', 'UBSAN']
```
