### ISSUE TITLE
Add more info to the log

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#44]
I think the log should include the method name.

For success/failure, it still needs to include method name and all args as well. It'll be easier to do analysis.

**Comment by everestmz** [comment]
By "method name" do you mean the last method called before the crash?

**Comment by tanin47** [comment]
No, I mean the word `reproduce`. We can call the field `command`

Ideally, this tool will have other action.

**Comment by everestmz** [comment]
Oh, I understand! I'll get that done before we publish the 0.1

**Comment by tanin47** [comment]
Ideally, we will query by `SELECT COUNT(DISTINCT user, testcase_id) FROM logs WHERE success='true';`, so it's important that all args are in the success records as well.

**Comment by everestmz** [comment]
Closed by #45
