### ISSUE TITLE
Need to inject the right libclang_rt.asan-arm-android.so when using downloaded build

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#442]
Because, when we run with a downloaded build, we need to install `libclang_rt.asan-arm-android.so` from the build zip (not from source).

**Comment by inferno-chromium** [comment]
s/libclang_rt.asan-arm-android.so/libclang_rt.asan-{arch}-android.so where arch can arm/aarch64, checkout code.

**Comment by tanin47** [comment]
Sorry about the vagueness. https://github.com/google/clusterfuzz-tools/blob/master/tool/clusterfuzz/resources/asan_device_setup.sh only needs the folder that contains both `*.so`, so I assume it automatically installs according to arch?

**Comment by inferno-chromium** [comment]
yes correct, just changing the folder path works for asan_device_setup.sh. we do an additional hack if libclang_rt.asan-aarch64-android.so (64-bit lib) does not exist in very old build, we copy it from local, so you might want to do the same.

**Comment by tanin47** [comment]
Ok, that might be tricky. For older testcases, we also don't have args.gn. I want to drop the support for older testcases. The workaround is to re-upload the testcases. I hope that sounds ok.

**Comment by inferno-chromium** [comment]
Yes lets stop supporting testcases that dont have args.gn and raise exception. or for those oneswe can change their crash_revision attribute value to last_tested_crash_revision. But lets not worry about uploads, that is too tedicious and manual.

**Comment by tanin47** [comment]
Thank you. This is implemented in #441.
