### ISSUE TITLE
4722047279431680 fails on CI because the dir structure for the layout test doesn't exist

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#465]
Our layout test hack wants to move the testcase file to an appropriate directory. However, the directory doesn't exist. Here's the error:

```
IOError: [Errno 2] No such file or directory: u'/usr/local/google/home/tanin/projects/chromium/src/third_party/WebKit/LayoutTests/imported/w3c/web-platform-tests/css/selectors/fuzz-84-focus-within-shadow-004.html
```

Let me think about how to handle this.

**Comment by inferno-chromium** [comment]
Should be a rare occurrence, hard to account for this niche scenario, can skip.

**Comment by tanin47** [comment]
That's true. It should stop occurring after we fixed the log-net-log.
