### ISSUE TITLE
Dont need to set ANDROID_SERIAL when there is only one device

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz-tools#476]
I get error when only one device is connected. There is no need to set ANDROID_SERIAL if there is only one device, ADB will use it automatically.

NoAndroidDeviceIdError: Please set the target Android device ID as the env ANDROID_SERIAL.

Probably, can just count lines from adb devices.

**Comment by inferno-chromium** [comment]
And also, move this check to start, rather than after building.

**Comment by tanin47** [comment]
> And also, move this check to start, rather than after building.

I'm on fence on this part. This would duplicate the code; it'd become harder to maintain. 

Back then, we wanted to move every check to the start (#222) as well (e.g. the location of the repo).  But we haven't done it yet because the downside is that the user needs to re-run it.

**Comment by inferno-chromium** [comment]
Thanks for fix.
