### ISSUE TITLE
Reproduce tool on Android does not git checkout chromium rev

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz-tools#482]
We only checkout clank revision in clank/ dir, however chromium rev is not checked out to correct revision. This will cause testcases to be not reproduced, and chromium rev is very important. Please fix.

vars = {
  "clank_revision": "160e9e18511a50d3b3b1f34affb415b728ecafba",
  "chromium_revision": "496287",
}

**Comment by tanin47** [comment]
We do git-checkout on Clankium/SRC/clank. Then, we run gclient sync. The
gclient sync should have checked out Clankium/SRC to the correct revision.

If it doesn't, it means, at some point, we ignore DEPS.

Will investigate more.

**Comment by inferno-chromium** [comment]
I first ran with --current to get latest chromium revision. Then ran without it.
Then I did git log on root src/ dir, it still says today's chromium revision, so chromium revision is definitely wrong.

**Comment by tanin47** [comment]
I think I remember why. Could you check the .gclient file? I remember
vaguely there is a setting that always sync everything to the latest SHA.
(In a Lyft, will look more in SF)

**Comment by inferno-chromium** [comment]
No rush, lets sync on friday.

This is what my .gclient looks like. If something needs to be changed, reproduce tool should do it automatically or else dev will never figure it out.

solutions = [
  { "name"        : "src/clank",
    "url"         : "<internal_repo_url>",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {
    },
  },
]
cache_dir = None

**Comment by tanin47** [comment]
We need to set `managed=False`.  `managed=True` will track ToT, and it has been deprecated (https://groups.google.com/a/google.com/forum/#!msg/chrome-infrastructure-team/fvTOzLOkhIk/4GXmlDcy8FAJ)

**Comment by inferno-chromium** [comment]
Since we get clankium src, we should fix it for use by asking to change .gclient file. I dont think all devs are using that, since it is in default instructions from wiki.

**Comment by tanin47** [comment]
Let's raise an exception for it. Fixing it automatically sounds dangerous. Also, could you confirm that `managed=False` solves this problem? Thank you

**Comment by inferno-chromium** [comment]
Yes it worked. Exception is fine to do.

**Comment by tanin47** [comment]
Here's another doc: https://www.chromium.org/developers/how-tos/get-the-code/gclient-managed-mode

One concern on this issue is that `managed` has been deprecated since 2014 (3 years ago). It's strange that we have to actively tell people not to use it.
