### ISSUE TITLE
Inconsistent behavior when llvm-symbolizer is not found

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz-tools#49]
For some reason, libFuzzer ASan build doesn't have `llvm-symbolizer`. What happens when I try to reproduce such testcase with `chromium` mode:

```
$ clusterfuzz reproduce 6083453533814784 -b chromium
Reproduce 6083453533814784 (current=False)
Downloading testcase information...
Running: python goma_ctl.py ensure_start
Using goma VERSION=122 (latest)
GOMA version 1058e0cf418d445b5735ab5243b31d887a1e8633@1487568363

goma is already running.

Downloading build data...
Running: gsutil cp gs://<...>.

| [1 files][  6.4 GiB/  6.4 GiB]   77.9 MiB/s                                   
Operation completed over 1 objects/6.4 GiB.                                      
Extracting...
Cleaning up...
Traceback (most recent call last):
  File "/usr/local/bin/clusterfuzz", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/main.py", line 42, in execute
    command.execute(**arg_dict)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/stackdriver_logging.py", line 89, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/commands/reproduce.py", line 246, in execute
    reproduce_crash(binary_provider.get_binary_path(),
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/binary_providers.py", line 109, in get_binary_path
    return '%s/%s' % (self.get_build_directory(), self.binary_name)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/binary_providers.py", line 231, in get_build_directory
    self.download_build_data()
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/binary_providers.py", line 106, in download_build_data
    os.chmod(symbolizer_location, stats.st_mode | stat.S_IEXEC)
OSError: [Errno 2] No such file or directory: '/usr/local/google/home/mmoroz/.clusterfuzz/builds/6083453533814784_build/llvm-symbolizer'
```

1) Why do we need llvm-symbolizer from the build, if I'm going to build fuzz target locally? My local checkout contains llvm-symbolizer and I think we should use it. + I think it's the plan to stop downloading the whole archive and use only args.gn file from the testcase? Thus, we shouldn't rely on the llvm-symbolizer from build archive.

2) I think it would be better to catch the exception and print only error message. Moreover, I think that it could be a WARNING message, and we can try to reproduce without the symbolizer anyway -- this is helpful so you can at least verify that crash happens + you can copy an exact command and run it manually then with a specified [symbolizer path](https://chromium.googlesource.com/chromium/src/+/master/testing/libfuzzer/reproducing.md#Symbolization).

3) When I try to reproduce this testcase with `download` mode, it doesn't say anything regarding llvm-symbolizer and simply works without symbolization.

**Comment by tanin47** [comment]
> I think it's the plan to stop downloading the whole archive and use only args.gn file from the testcase?

Yes, especially now that we can get `args.gn` from the testcase detail.

> Why do we need llvm-symbolizer from the build, if I'm going to build fuzz target locally?

This has been a dilemma. We want to use the llvm-symbolizer from that point of time. However, we have been tool multiple times that llvm-symbolizer doesn't change often.

I think we will switch this to use ENV variable instead and let user define the path of llvm-symbolizer. Thanks for the instruction on the symbolizer path!

> For some reason, libFuzzer ASan build doesn't have llvm-symbolizer

I see that all buildbot makes an explicit step to copy llvm-symbolizer into the zip file. I guess this build is just too old; it's from Oct 2016.

> When I try to reproduce this testcase with download mode, it doesn't say anything regarding llvm-symbolizer and simply works without symbolization.

That's really strange. I'll investigate.

**Comment by everestmz** [comment]
The reason it can't find llvm-symbolizer and actually throws an exception the first time is because it actively tries to `chmod` the symbolizer the first time it downloads a build. 

When you ran with `-b download` the build had already been downloaded. As soon as it sees the build folder is there, it assumes everything is inside & working, and then just sets the `ASAN_SYMBOLIZER_PATH` environment variable. So it reproducing without symbolization is expected the way the tool currently works.

I agree the right course of action is to ask the user for the symbolizer's location via an environment variable.

**Comment by tanin47** [comment]
Ok, got it. Thanks for investigating.

**Comment by inferno-chromium** [comment]
keep a copy of llvm-symbolizer with your tool. we do that with clusterfuzz too. and then *_OPTIONS should use your symbolizer path.

**Comment by everestmz** [comment]
#82 packages llvm-symbolizer
