### ISSUE TITLE
sudo install-build-deps-android.sh complains about java

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#497]
It turns out that `sudo` resets `PATH` to `/usr/sbin:/usr/bin:/sbin:/bin`.

This complains about Java's version because `java` in `/usr/bin` is Java 7. But, actually, we are using Java in `/usr/local/buildtools/java/jdk/bin`; this is Java 8.

Therefore, we need to inject our `PATH` into `sudo`. We can do that with `sudo PATH=$PATH build/install-build-deps-android.sh`.

**Comment by inferno-chromium** [comment]
Wont we have the same issue with user running the reproduce tool locally ?

**Comment by tanin47** [comment]
Yes, this error occurred on user's machine (my machine), not the CI.

**Comment by inferno-chromium** [comment]
Cool, thanks for fix.
