### ISSUE TITLE
Tool doesn't preserve terminal colored text

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz-tools#50]
ASan and other memory tools print pretty neat colored reports, e.g.: 
![image](https://cloud.githubusercontent.com/assets/3372458/23502696/fba9b520-ff38-11e6-9c7e-6a1e570176c6.png)

Our tool doesn't preserve these colors from ASan and friends:
![image](https://cloud.githubusercontent.com/assets/3372458/23502727/18cda01c-ff39-11e6-8757-8734905bc5db.png)

Would it be hard to print a colored crash info?

**Comment by tanin47** [comment]
After googling a bit, this might be impossible :S 

https://stackoverflow.com/questions/13299550/preserve-colored-output-from-python-os-popen, https://stackoverflow.com/questions/38084815/can-you-have-subprocesss-popen-retain-color-in-stdout-stderr, https://stackoverflow.com/questions/42589584/ansi-color-lost-when-using-python-subprocess

It doesn't make sense that there's no easy way of doing this.

**Comment by Dor1s** [comment]
![okay](https://user-images.githubusercontent.com/3372458/26890078-320ba3ee-4b65-11e7-9af3-8e0a6281be84.jpg)
