### ISSUE TITLE
Decide how to handle the default value for --build

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#52]
There are multiple designs:

1. Default to `chromium` or `standalone`. This will fail on certain job, e.g. libfuzzer_asan_chrome doesn't support `standalone`.
2. We can default based on job type. But that will add more code and more tests. This is a nice polish UX. We will eventually implement this later in time.
3. We can require the flag, and user has to think about the flag.

**Comment by everestmz** [comment]
It may be useful to just require the flag, so the command is always explicit and the user knows exactly what they're running every time.

**Comment by tanin47** [comment]
I agree that the option 3 is the lowest effort (one line change) we can do right now to avoid confusion.

We can decide to implement the option 2 later when we have more free time.

**Comment by everestmz** [comment]
I think that's the way to go right now - force them to select a flag.
