### ISSUE TITLE
Unable to access test case

### ISSUE THREAD

**Issue by mfoltzgoogle** [google/clusterfuzz-tools#531]
I am working on https://bugs.chromium.org/p/chromium/issues/detail?id=797173, however, following the instructions here.  I can visit the test case in my browser, but when I try to access it through the command line tool it asks me for a token over and over again.  Here is the output with the tokens removed.

https://pastebin.com/DuFbyZ78

Is there some issue with authentication?  Can I authenticate to the tool in some other way?

**Comment by inferno-chromium** [comment]
Are you logging with your @chromium.org account ?

**Comment by mfoltzgoogle** [comment]
Yes, the URL pulls up the account chooser, and I was picking mfoltz@chromium.org.
I think I tried my @google.com account on the last attempt though.

**Comment by mfoltzgoogle** [comment]
Well, it looks like the underlying clusterfuzz bug has been fixed, so there's no reason for me to use this tool at present.  If I need it again, I guess I'll see what happens.
