### ISSUE TITLE
Can't build in OSX Mojave!

### ISSUE THREAD

**Issue by caitp** [google/clusterfuzz-tools#538]
Per https://github.com/pantsbuild/pants/pull/6591, I've worked around this by switching to pants 1.9.0, and updating the python_library call to the new supported arguments, and adding a new resources() target/dependency to replace the `resources` argument that is no longer supported.

Building seems to be necessary because the pre-packaged 2.6.0 build is not happy with the requirements installed on my mac, even though they are present! But, with my own build, the dependencies are found and work just fine.

If anybody else encounters these problems on their macs, it might be worth migrating to pants 1.9.0 upstream?

**Comment by inferno-chromium** [comment]
Can you please submit a pull request with your changes. So, reproduce tool works end-to-end for you with the changes you made ?
