### ISSUE TITLE
Windows documentation is lacking

### ISSUE THREAD

**Issue by mfreed7** [google/clusterfuzz-tools#552]
I have a [clusterfuzz issue](https://clusterfuzz.com/testcase-detail/5651885067993088) that is an unreproducable Windows ASAN. So I'm trying to follow the [manual instructions](https://chromium.googlesource.com/chromium/src/+/master/testing/libfuzzer/reproducing.md). Those call for gsutil, which I don't have on my Windows machine. So I installed it. And then gcloud init asks me "which project". And helpfully lists the 900 projects available. None have the word "cluster" in them. Which one should I use?

**Comment by mfreed7** [comment]
While I'm commenting on documentation, [the instructions](https://chromium.googlesource.com/chromium/src/+/master/testing/libfuzzer/reproducing.md) say this: "$FUZZER_NAME (provided as “Fuzz target binary” in the bug description)". However, there is no such field on either the crbug.com entry or the [clusterfuzz testcase](https://clusterfuzz.com/testcase-detail/5651885067993088) detail. The closest thing is "Fuzzer" which is "inferno_layout_test_fuzzer" but that does not appear to work. Neither does the job type, "windows_asan_content_shell". At this point I'm assuming plain old "content_shell" is the right target, but I'll only know after I wait for that to build.

**Comment by inferno-chromium** [comment]
Manual instructions at https://chromium.googlesource.com/chromium/src/+/master/testing/libfuzzer/reproducing.md are for libFuzzer, AFL testcases, not regular blackbox fuzzers.

We are planning to deprecate this confusing reproduce tool repo this quarter. Given clusterfuzz itself is now open-source, we plan to rewrite the reproduce tool and be a part of clusterfuzz repo as well.
